name: 🚀 Deploy on staging

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: 📂 Setup
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ checkout
        uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
  
  deploy-ghpages:
    name: 🚀 Deploy gh-pages
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 deploy on gh-pages
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_env: development
  
  deploy-staging:
    name: 🚀 Deploy staging
    needs: deploy-ghpages
    runs-on: ubuntu-latest
    steps:
      - name: 🔨 build staging
        uses: helaili/jekyll-action@v2
        with:
          build_only: true

      - name: 🔐 Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: 🎯 Adding Known Hosts
        run: ssh-keyscan -H staging.agilebrazil.com >> ~/.ssh/known_hosts
      
      - name: 🚀 deploy on staging
        run: rsync -zav --progress --delete -e 'ssh -o StrictHostKeyChecking=no' build/ agilebrazil@staging.agilebrazil.com:staging.agilebrazil.com/2021
