name: 🚀 Deploy on staging (GH-PAGES)

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 setup
        uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      #- name: 🔨 install dependencies & build site
      #  uses: limjh16/jekyll-action-ts@v2
      #  with:
      #    enable_cache: true
      #    custom_opts: 'JEKYLL_ENV=development'
      
      - name: 🚀 deploy on gh-pages
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} #build_only: true
          jekyll_env: development

      #- name: 🚀 deploy on gh-pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./_site

      - name: 🔨 build staging
        uses: helaili/jekyll-action@v2
        with:
          build_only: true
      
      - name: 🚀 deploy on staging
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: ./_site
          remote_path: /var/www/html/
          remote_host: staging.agilebrazil.com/2021
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
